const ScreenNames = {
  LOGIN: "Login",
  HOME: "Home",
  GETTINGLOGIN: "GettingLogin",
  GETTINGSTARTED: "GettingStarted",
  RESETPASSWORD: "ResetPassword",
  CREATEACCOUNT: "CreateAccount",
  PRIVACYPOLICY: "PrivacyPolicy",
  TERMSANDCONDITIONS: "TermsAndConditions",
  COMPLETEPROFILE: "CompleteProfile",
  VERIFICATIONCODE: "VerificationCode",
  UPLOADPICTURES: "UploadPictures",
  LOCATIONSCREEN: "locationScreen",
  IDENTITYVERIFICATION: "IdentityVerification",
  SERVICEAREAS: "ServiceAreas",
  SELECTRADIUS: "SelectRadius",
  PDFFORM: "PdfForm",
  HOMESCREEN: "HomeScreen",
  ORDERSCREEN: "OrderScreen",
  PROFILESCREEN: "ProfileScreen",
  DATESCREEN: "DateScreen",
};
export default ScreenNames;
